#!/usr/bin/env bash
# One-shot setup for a rented Vast.ai instance.
#
# Run this ON the rented machine, from the project directory:
#   bash deploy/install-on-vast.sh
#
# It installs Python dependencies, builds the worker for the GPU in this box,
# and prints the command that starts the controller. It does not start mining,
# does not import a key, and does not set a spending cap -- those are operator
# decisions made through the panel.
set -euo pipefail

cd "$(dirname "$0")/.."
ROOT="$(pwd)"

echo "== MinerPotatos setup on $(hostname) =="
echo

# ------------------------------------------------------------------ toolchain
if ! command -v python3 >/dev/null 2>&1; then
  echo "python3 is required but not installed." >&2
  exit 1
fi
echo "python3: $(python3 -V 2>&1)"

if ! command -v nvcc >/dev/null 2>&1 && [ -x /usr/local/cuda/bin/nvcc ]; then
  echo "adding /usr/local/cuda/bin to PATH for this session"
  export PATH="/usr/local/cuda/bin:$PATH"
fi

if command -v nvidia-smi >/dev/null 2>&1; then
  echo
  echo "== GPUs visible to the driver =="
  nvidia-smi --query-gpu=index,name,compute_cap,memory.total \
    --format=csv,noheader || echo "(nvidia-smi query failed)"
  GPU_COUNT="$(nvidia-smi --query-gpu=index --format=csv,noheader | wc -l | tr -d ' ')"
else
  echo "WARNING: nvidia-smi not found. The controller can still run with the"
  echo "         CPU reference build, but it will not mine usefully."
  GPU_COUNT=0
fi

# --------------------------------------------------------------- dependencies
echo
echo "== installing Python dependencies =="
python3 -m pip install --quiet --upgrade pip
python3 -m pip install --quiet -r requirements.txt
python3 -m pip freeze | grep -Ei 'eth-account|eth-abi|eth-utils|pycryptodome' || true

# --------------------------------------------------------------------- build
echo
echo "== building the worker =="
bash worker/build.sh miner

# -------------------------------------------------------------- sanity checks
echo
echo "== verifying the build against the live contract =="
python3 - <<'PY'
import sys
sys.path.insert(0, "controller")
import protocol as P

c = P.Contract()
chain = c.chain_id()
code = c.code_hash().hex()
print(f"chain id      {chain}")
print(f"contract      {P.CONTRACT}")
print(f"code hash     {code[:24]}...")

if chain != P.CHAIN_ID:
    print(f"FAIL: expected chain {P.CHAIN_ID}, got {chain}")
    sys.exit(1)

st = c.mining_status()
print(f"read at block {st['_block']} anchorBlock {st['anchorBlock']}")
print(f"target        {P.effective_bits(st['target']):.2f} bits")
print(f"price         {st['price'] / 1e18} ETH")
print(f"supply        {st['supply']} / {st['maxSupply']}")

# The decisive check: our preimage layout must equal the contract's own
# pure function, on state read from a single pinned block.
import secrets
miner = "0x" + "11" * 20
nonce = secrets.token_bytes(32)
local = P.work_of(miner, st["prevWork"], st["anchor"], nonce)
remote = c.work_for(miner, st["prevWork"], st["anchor"],
                    int.from_bytes(nonce, "big"), st["_block"])
if local != remote:
    print("FAIL: local preimage does not match contract workFor()")
    sys.exit(1)
print("preimage      matches contract workFor() on live state")
if st["anchor"] != c.block_hash(st["anchorBlock"]):
    print("WARNING: anchor is not blockhash(anchorBlock) -- investigate")
else:
    print("anchor        equals blockhash(anchorBlock)")
PY

# ------------------------------------------------------------- run directory
mkdir -p logs
cat > .env <<EOF
# Generated by deploy/install-on-vast.sh -- edit if needed.
MP_GPU_COUNT=$GPU_COUNT
MP_BINARY=$ROOT/worker/miner
MP_PANEL_PORT=8901
MP_DASHBOARD_PORT=8903
EOF

echo
echo "== setup complete =="
echo
echo "GPUs detected: $GPU_COUNT"
echo
echo "Start the controller (enrolls every visible GPU):"
ARGS=""
for ((i = 0; i < GPU_COUNT; i++)); do ARGS="$ARGS --device $i"; done
echo "  python3 controller/panel.py --binary $ROOT/worker/miner$ARGS"
echo
echo "It prints a URL with a token in the fragment. That token is the only"
echo "authentication, so keep the terminal private."
echo
echo "If you are connecting over SSH, forward the port from your own machine:"
echo "  ssh -p <PORT> -L 8901:127.0.0.1:8901 root@<HOST>"
echo "then open  http://127.0.0.1:8901/#token=<TOKEN>  locally."
echo
echo "Nothing spends until you set a cap and import a key in the panel."
